"""Conteúdo dos stories bônus. Cada item vira um story; os datados vão para o dia certo."""

TIPS = [
("Anote o gasto _na hora._", "Deixar para depois é o jeito mais rápido de esquecer."),
("Tenha um _dia fixo_ para olhar as finanças.", "15 minutos por semana já mudam o jogo."),
("Antes de comprar, espere _24 horas._", "Se a vontade passar, era impulso."),
("Pague a fatura _inteira._", "O rotativo é um dos créditos mais caros que existem."),
("Assinatura que você não usou no mês? _Cancela._", "Dá para assinar de novo quando quiser."),
("Guarde _antes_ de gastar.", "Separe o valor da reserva assim que o salário cair."),
("Compare o preço _por quilo._", "A embalagem maior nem sempre sai mais barata."),
("Mercado com fome = _carrinho cheio._", "Coma antes de ir às compras."),
("Lista de compras _é lei._", "O que não está na lista espera a próxima ida."),
("Todo gasto pequeno _conta._", "É ele que some sem você perceber."),
("Defina um _teto_ para o lazer.", "Dá para curtir sem estourar o mês."),
("Frete grátis não é desconto se você _comprou mais_ para ganhar.", ""),
("Parcela pequena, _compromisso longo._", "Some todas as parcelas antes de fazer mais uma."),
("Revise os _débitos automáticos._", "Às vezes tem cobrança que você nem lembra."),
("Separe o dinheiro das _contas fixas_ primeiro.", "O que sobra é o que você pode gastar."),
("Troque “quanto custa?” por _“quanto custa por mês?”_", "Assinaturas e parcelas ficam mais claras."),
("Cheque especial _não é saldo._", "É empréstimo, e caro."),
("Uma meta _com nome_ é mais fácil de cumprir.", "“Viagem de julho” motiva mais do que “guardar dinheiro”."),
("Leve _marmita_ dois dias por semana.", "No fim do mês, a diferença aparece."),
("Negocie a _internet e o celular_ uma vez por ano.", "Planos mudam, e o seu pode estar caro."),
("Promoção boa é a de algo que você _já ia comprar._", ""),
("Confira a fatura _linha por linha._", "Cobrança estranha se contesta, não se paga."),
("Tenha _uma conta_ só para a reserva.", "Longe dos olhos, longe do gasto."),
("Registre também as _receitas._", "Freela, venda, presente: tudo entra no controle."),
("Categoria “Outros” grande demais?", "É sinal de que falta uma categoria nova."),
("Pequeno aumento de salário? _Aumente o quanto guarda._", "Antes que o padrão de vida suba sozinho."),
("Delivery _toda semana_ vira uma conta fixa.", "Vale colocar um limite."),
("Não compre _para compensar_ um dia ruim.", "Um passeio ou um banho demorado também resolvem."),
("Saiba o _dia de fechamento_ do seu cartão.", "Comprar logo depois dele dá mais prazo para pagar."),
("Menos cartões, _mais controle._", "Dois bem usados valem mais do que cinco esquecidos."),
("Sobrou dinheiro no mês? _Dê um destino_ para ele.", "Senão ele encontra um sozinho."),
("Presente caro não é sinônimo de _presente bom._", ""),
("Faça as contas do _custo por uso._", "Um tênis de R$ 300 usado 300 vezes custa R$ 1 por uso."),
("Evite o _“já que”_.", "“Já que estou aqui, vou levar…” é o começo de muitos gastos."),
("Troque marca por _qualidade._", "Nem tudo precisa ser da marca mais famosa."),
("Vai viajar? _Crie a meta antes._", "Viagem paga antes de sair é outra viagem."),
("Organize as contas por _data de vencimento._", "Nada de multa por esquecimento."),
("Divida o que sobra pelos _dias do mês._", "Fica mais fácil ver quanto dá para gastar por dia."),
("Não use o _limite do cartão_ como meta.", "Limite é teto, não sugestão."),
("Todo _começo de mês_, olhe as metas.", "Um minuto para lembrar para onde você está indo."),
("Anote _quanto você gasta em transporte._", "Aplicativo, combustível e estacionamento somam rápido."),
("Pague _à vista_ quando tiver desconto.", "E quando o dinheiro já estiver separado."),
("Fez uma dívida? _Registre as parcelas._", "Ver o que vem pela frente evita susto."),
("Tenha um _valor livre_ por semana.", "Gastar sem culpa também faz parte do plano."),
("Compras online: _deixe no carrinho_ um dia.", "Se ainda fizer sentido amanhã, compre."),
("Reveja o _plano de saúde_ e os seguros.", "Compare coberturas antes de renovar."),
("Guarde _os comprovantes_ de saúde e educação.", "Na hora do Imposto de Renda você agradece."),
("Evite sacar dinheiro _sem destino._", "Dinheiro vivo some mais rápido."),
("Conversa sobre dinheiro em casa _não é tabu._", "Todo mundo remando para o mesmo lado."),
("Aumente o valor guardado _aos poucos._", "R$ 10 a mais por mês já é progresso."),
("Um gasto que te incomoda?", "_Registre por 30 dias_ e veja o tamanho real."),
("Pagou o mínimo da fatura?", "_Troque o rotativo_ por um parcelamento mais barato."),
("Compare _pelo menos 3 lojas_ antes de uma compra grande.", ""),
("Comprou algo por impulso?", "_Tudo bem._ Registre e siga em frente."),
("Tenha _uma meta curta_ e uma longa.", "A curta mantém a motivação. A longa, o rumo."),
("Seu futuro eu _agradece_ cada real guardado hoje.", ""),
("Antes de parcelar, pergunte:", "_Eu compraria isso à vista?_"),
("Não empreste o _nome_ nem o _cartão._", "Dívida de outra pessoa vira sua."),
("O melhor desconto é _não precisar_ da compra.", ""),
("Fim de semana também é _dia de registrar._", "É quando mais escapa gasto pequeno."),
("Crie uma categoria para _presentes._", "Aniversários chegam todo ano, e sempre na mesma data."),
("_Reserva de emergência_ é para emergência.", "Promoção não é emergência."),
("Olhe o gasto do mês _pela metade do mês._", "Dá tempo de corrigir a rota."),
("Tarifa bancária pesando?", "_Existem contas digitais_ sem mensalidade."),
("Troque o café na rua por _um dia sim, um dia não._", "Não precisa cortar tudo para economizar."),
("Evite comprar _cansado._", "Decisão de fim de dia costuma sair cara."),
("Prefira _poucas metas_ bem definidas.", "Dez metas ao mesmo tempo viram nenhuma."),
("Salário variou?", "_Planeje pelo menor valor_ dos últimos meses."),
("Pagamento extra?", "_Metade guarda, metade aproveita._ Todo mundo sai feliz."),
("Desconfie de _“só hoje”._", "Urgência é a ferramenta favorita de quem vende."),
("Não precisa ser _perfeito._", "Precisa ser _constante._"),
("Revise as _metas_ a cada trimestre.", "A vida muda, e o plano também pode mudar."),
("Anote o que _entrou_ e o que _saiu._", "O resto é consequência."),
("_Planilha abandonada_ não organiza nada.", "O melhor controle é o que você consegue manter."),
("Guarde o _troco digital._", "Arredondar compras e guardar a diferença também conta."),
("Gastos anuais?", "_Divida por 12_ e separe um pouco todo mês."),
("IPVA, IPTU, matrícula…", "_Comece a separar_ meses antes."),
("Planeje as _férias_ com antecedência.", "Passagem comprada cedo costuma sair mais barata."),
("Toda compra grande merece uma _pesquisa de preço._", ""),
("Cartão de loja com desconto?", "_Mais um cartão_ é mais uma fatura para controlar."),
("Economizou em algo?", "_Transfira o valor_ para a meta na hora."),
("Evite _misturar_ as contas da empresa com as pessoais.", ""),
("Não deixe o dinheiro da meta _na conta corrente._", "Fica fácil demais gastar."),
("Aprenda a dizer _“esse mês não dá”._", "Sem culpa."),
("Revise os _gastos com pets._", "Ração, banho e veterinário também merecem categoria."),
("Anote os gastos com _filhos._", "Escola, lanche e atividades somam mais do que parece."),
("Controle financeiro _não é dieta._", "É saber para onde vai, e escolher."),
("Comemore quando _bater uma meta._", "Com um valor que já estava planejado."),
("Evite empréstimo para _consumo._", "Pagar juros para comprar algo que perde valor raramente vale."),
("Dinheiro guardado _tem que ter nome._", "Reserva, viagem, carro… cada um no seu lugar."),
("Um bom começo:", "_Guardar 10%_ de tudo o que entra."),
("Reveja o _orçamento_ quando a vida mudar.", "Casamento, filho, emprego novo, mudança de casa."),
("_Um passo por vez._", "Arrume uma categoria por mês."),
("Troque _“mereço”_ por _“planejei”._", "Gastar com prazer é melhor quando cabe no plano."),
("Faça uma _semana sem gastos extras._", "Só o essencial. Depois conte quanto sobrou."),
("Aniversário de alguém?", "_Combine o valor_ do presente coletivo antes."),
("Seguro do carro vencendo?", "_Faça 3 cotações_ antes de renovar."),
("Guarde o _13º_ antes de gastar.", "Decida o destino dele com calma."),
("Cashback e pontos _ajudam_, mas não justificam gastar mais.", ""),
("Vendeu algo usado?", "_Mande o valor direto_ para uma meta."),
("Recebeu restituição do IR?", "_Dê um destino_ antes de ela sumir."),
("Revise os _gastos do semestre_ em julho.", "Metade do ano é ótimo momento para ajustar."),
("Controle não é _restrição._", "É liberdade para gastar no que importa."),
("Conta de luz alta?", "_Aparelhos em standby_ também consomem."),
("Não existe _gasto invisível._", "Existe gasto não anotado."),
]

QUESTIONS = [
("Qual gasto você _mais se arrepende_ este mês?", "Sem julgamento, todo mundo tem um."),
("Você já tem uma _reserva de emergência?_", "Conta pra gente em que pé está."),
("Qual é a sua _meta_ para o fim do ano?", "Escrever ajuda a cumprir."),
("Quanto você acha que gasta com _delivery_ por mês?", "Chuta um valor."),
("Você prefere _pagar à vista_ ou _parcelar?_", "E por quê?"),
("Qual _assinatura_ você cancelaria hoje?", ""),
("Você _confere a fatura_ antes de pagar?", "Sempre, às vezes ou nunca?"),
("Qual foi a sua _melhor compra_ do ano?", "Aquela que valeu cada centavo."),
("Você já _desistiu de uma planilha?_", "Quantas vezes? 😅"),
("O que te faz _gastar por impulso?_", "Tédio, cansaço, promoção…"),
("Você conversa sobre dinheiro _em casa?_", ""),
("Qual _hábito financeiro_ você quer criar?", ""),
("Você sabe o _dia de fechamento_ do seu cartão?", "Sem olhar no app!"),
("Se ganhasse R$ 1.000 extras hoje, _o que faria?_", ""),
("Qual categoria mais _pesa_ no seu mês?", ""),
("Você tem uma _meta de viagem?_", "Para onde?"),
("Você anota os _gastos pequenos?_", "Cafezinho, estacionamento, lanche…"),
("Qual dica de finanças _mudou a sua vida?_", ""),
("Você já caiu em _promoção falsa?_", "Conta como foi."),
("Com quantos anos você começou a _guardar dinheiro?_", ""),
("Qual é o seu _maior desafio_ com dinheiro hoje?", ""),
("Você usa _quantos cartões_ de crédito?", ""),
("O que você quer ver _mais por aqui?_", "Dicas, app, desafios…"),
("Você já fez o _desafio das 52 semanas?_", ""),
("Qual gasto você _cortou_ e nem sentiu falta?", ""),
("Você prefere _guardar para um sonho_ ou _investir_ direto?", ""),
("Qual foi a sua _maior conquista financeira?_", "Toda conquista conta."),
("Você já teve que usar a _reserva?_", "Ela salvou o dia?"),
("Como você _divide as contas_ em casa?", ""),
("Você tem um _dia fixo_ para pagar as contas?", ""),
("Qual app você _abre mais_ no celular?", "E quanto ele te custa por mês?"),
("Você já comprou algo e _devolveu_ no prazo?", ""),
("Qual _despesa inesperada_ mais te pegou este ano?", ""),
("Você acompanha os seus _gastos pelo celular?_", ""),
("Qual seria a sua _primeira meta_ no Wally?", ""),
("Você já _negociou_ uma conta fixa?", "Internet, celular, seguro…"),
("Você tem _dinheiro guardado_ para presentes?", ""),
("Qual _pergunta sobre finanças_ você nunca teve coragem de fazer?", "Pode mandar."),
("Você gasta mais no _cartão_ ou no _Pix?_", ""),
("O que te _motiva_ a guardar dinheiro?", ""),
]

NUMS = [
("R$ 15 por dia", "viram **R$ 5.475** em um ano.", "Parece pouco"),
("30 dias", "de registros bastam para você enxergar seus hábitos.", ""),
("3 a 6", "meses de custo de vida: é o alvo comum da reserva de emergência.", ""),
("R$ 1.378", "é o total do desafio das 52 semanas.", ""),
("5s", "para registrar um gasto no Wally pelo Telegram.", ""),
("72h", "de espera antes de uma compra fora do plano.", "A regra das"),
("50·30·20", "necessidades, desejos e futuro. Um ponto de partida para dividir a renda.", ""),
("7 dias", "para desistir de uma compra feita fora da loja física.", "Você tem"),
("R$ 40 por mês", "de assinatura esquecida são **R$ 480** no ano.", ""),
("1 em cada 10", "reais guardados já é um começo. Comece pelos 10%.", ""),
("R$ 25", "de delivery 3x por semana são **R$ 300** por mês.", ""),
("12x", "sem juros ainda são 12 meses de compromisso.", ""),
("15 min", "por semana é o tempo de uma boa revisão das finanças.", ""),
("R$ 5", "também é gasto. E é o que mais escapa.", ""),
("80%", "do limite do orçamento? O Wally te avisa no Telegram.", ""),
("R$ 0", "para começar a usar o Wally.", ""),
("R$ 19,90", "por mês é o Wally Pro, com o bot de IA no Telegram.", ""),
("2 cartões", "bem controlados valem mais do que 5 esquecidos.", ""),
("R$ 100", "guardados por mês viram **R$ 1.200** no ano, sem contar rendimento.", ""),
("365", "chances por ano de registrar um gasto. Hoje é uma delas.", ""),
("6 meses", "de fluxo de receitas e despesas no painel do Wally.", ""),
("1 mensagem", "e o gasto está registrado e categorizado.", "Basta"),
("3, 6 ou 12", "meses de relatórios para comparar no Wally.", ""),
]

MITOS = [
("Quem ganha bem não precisa controlar gastos.", "Quanto mais entra, **mais fácil** escapar sem perceber."),
("Guardar pouco não adianta.", "**Pouco todo mês** vira muito com o tempo."),
("Controle financeiro é chato.", "Chato é **não saber** para onde foi o dinheiro."),
("Parcelar sem juros é sempre bom.", "Só se as parcelas **couberem** nos próximos meses."),
("Cartão de crédito é vilão.", "O vilão é o **descontrole**."),
("Planilha é o único jeito de se organizar.", "O melhor jeito é **o que você mantém**."),
("Reserva de emergência é para quem tem sobra.", "É justamente para **não depender** de empréstimo."),
("Economizar é cortar tudo.", "É **escolher** onde vale gastar."),
("Não tenho dívida, então estou bem.", "Sem reserva, **um imprevisto** vira dívida."),
("Só dá para investir com muito dinheiro.", "Há opções com **valores baixos**. O importante é começar."),
("Pix não conta como gasto.", "Pix, débito, crédito: **tudo sai do mesmo bolso.**"),
("Limite do cartão é dinheiro disponível.", "Limite é **crédito**, não saldo."),
("Dinheiro na conta corrente está guardado.", "Está é **fácil de gastar.**"),
("Organizar as finanças leva horas.", "Com o Wally, **segundos por gasto.**"),
("Falar de dinheiro é falta de educação.", "Falar de dinheiro **evita problema.**"),
("Promoção sempre é economia.", "Só se você **já ia comprar.**"),
("Imposto de Renda é só para rico.", "A obrigação depende de **vários critérios.** Confira as regras."),
("Não dá para organizar com renda variável.", "Dá, e é **ainda mais importante.**"),
]

LISTS = [
("3 contas para _revisar hoje_", "Planejamento", ["Internet e celular", "Assinaturas", "Tarifas do banco"]),
("Para _começar a semana_", "Planejamento", ["Veja o saldo", "Confira os vencimentos", "Defina o valor livre da semana"]),
("Antes de _pagar a fatura_", "Cartão", ["Confira cada compra", "Veja se tem parcela nova", "Pague o valor total"]),
("Checklist de _fim de mês_", "Revisão", ["Registrei tudo?", "Estourei algo?", "Guardei alguma coisa?"]),
("3 perguntas antes de _comprar_", "Consumo", ["Eu preciso?", "Cabe no mês?", "Achei o melhor preço?"]),
("Montando a _reserva_", "Reserva", ["Calcule o custo de vida", "Defina o alvo", "Guarde todo mês"]),
("Para _sair do vermelho_", "Dívidas", ["Liste as dívidas", "Priorize os juros altos", "Negocie"]),
("Metas que _funcionam_", "Metas", ["Nome", "Valor", "Prazo"]),
("Onde o _dinheiro escapa_", "Gastos", ["Delivery", "Assinaturas", "Compras por impulso"]),
("Para economizar _no mercado_", "Mercado", ["Lista", "Comer antes", "Preço por quilo"]),
("Contas de _começo de ano_", "Planejamento", ["IPVA", "IPTU", "Material escolar"]),
("Presentes _sem apertar_", "Presentes", ["Lista de nomes", "Valor por pessoa", "Comprar cedo"]),
("Viagem _planejada_", "Viagem", ["Orçamento total", "Meta no Wally", "Reserva antecipada"]),
("Rotina de _5 minutos_", "Hábitos", ["Registrar", "Olhar o saldo", "Checar o orçamento"]),
("Sinais de _golpe_", "Segurança", ["Urgência", "Pedido de senha", "Ganho fácil"]),
("Para _renda variável_", "Planejamento", ["Renda média", "Salário fixo para você", "Reserva maior"]),
("Casal que _se organiza_", "Finanças a dois", ["Conversa aberta", "Metas juntos", "Divisão combinada"]),
]

APP = [
dict(title="Registre um gasto _com uma mensagem._", msgs=[["u", "mercado 187,40"], ["card", {"icon": "🛒", "name": "Mercado", "cat": "Alimentação · Hoje", "amt": "187,40", "inc": False}]]),
dict(title="Recebeu? _Manda também._", msgs=[["u", "recebi 1500 do freela"], ["card", {"icon": "💼", "name": "Freela", "cat": "Rendimentos · Hoje", "amt": "1.500,00", "inc": True}]]),
dict(title="Quanto ainda _dá para gastar?_", sub="O Wally faz a conta por dia.", img="posso-gastar"),
dict(title="Seu mês _numa tela._", img="dash-top"),
dict(title="Para onde _foi o dinheiro?_", img="categorias"),
dict(title="Compare _mês a mês._", img="comparacao"),
dict(title="Veja o patrimônio _crescer._", img="patrimonio"),
dict(title="Gastos por categoria, _num gráfico._", img="rel-cat"),
dict(title="Mande _/saldo_ e veja o mês.", msgs=[["u", "/saldo"], ["wt", "📊 **Resumo do mês**\nReceitas: R$ 5.200,00\nDespesas: R$ 2.310,50\nSaldo do mês: R$ 2.889,50"]]),
dict(title="Escreva _do seu jeito._", msgs=[["u", "uber 23,90"], ["card", {"icon": "🚗", "name": "Uber", "cat": "Transporte · Hoje", "amt": "23,90", "inc": False}]]),
dict(title="Contas da casa, _registradas._", msgs=[["u", "conta de água 96,40"], ["card", {"icon": "💧", "name": "Conta de água", "cat": "Moradia · Hoje", "amt": "96,40", "inc": False}]]),
dict(title="A IA _escolhe a categoria._", msgs=[["u", "remédio 42"], ["card", {"icon": "💊", "name": "Remédio", "cat": "Saúde · Hoje", "amt": "42,00", "inc": False}]]),
dict(title="Comandos _rápidos._", msgs=[["u", "/despesa 30 Lanche"], ["card", {"icon": "🥪", "name": "Lanche", "cat": "Alimentação · Hoje", "amt": "30,00", "inc": False}]]),
dict(title="Orçamento _perto do limite?_", sub="O Wally te avisa no Telegram.", msgs=[["wt", "⚠️ **Orçamento de Compras**\nVocê está em **85%** do limite deste mês."]]),
dict(title="Compras do cartão _no mês da fatura._", sub="Assim o painel mostra o que sai da conta de verdade."),
dict(title="Parcelou? _Cada parcela no seu mês._", sub="Os próximos meses já mostram o que está comprometido."),
dict(title="Metas com _barra de progresso._", sub="Crie, deposite e veja chegando a 100%."),
dict(title="Exporte _para Excel._", sub="Todos os lançamentos do período, com um clique. No Pro."),
dict(title="Modo _escuro_ também.", sub="Claro, escuro ou automático."),
dict(title="Categorias _com a sua cara._", sub="Renomeie, crie novas e escolha a cor."),
dict(title="Verificação _em duas etapas._", sub="Um código por e-mail para proteger sua conta."),
dict(title="Sem acesso _à sua conta bancária._", sub="Você registra só o que quiser."),
dict(title="Dá para _editar pelo Telegram._", msgs=[["u", "/listar"], ["wt", "🧾 **Últimos lançamentos**\n1. Mercado · − R$ 187,40\n2. Uber · − R$ 23,90\n\nToque em um para editar ou apagar."]]),
dict(title="Vários cartões, _cada um com sua fatura._", sub="Fechamento e vencimento separados. No Pro."),
dict(title="Relatórios de _3, 6 ou 12 meses._", img="rel-top"),
dict(title="O Wally _no celular._", sub="Tudo pelo navegador, com menu fácil de alcançar."),
dict(title="Gastou no fim de semana?", sub="_Registre em segundos,_ mesmo depois.", msgs=[["u", "cinema sábado 64"], ["card", {"icon": "🎬", "name": "Cinema", "cat": "Lazer · Hoje", "amt": "64,00", "inc": False}]]),
dict(title="Gasto do _cafezinho_ também.", msgs=[["u", "café 7,50"], ["card", {"icon": "☕", "name": "Café", "cat": "Alimentação · Hoje", "amt": "7,50", "inc": False}]]),
dict(title="Transações _organizadas._", img="dash-bottom"),
dict(title="Comece _grátis._", sub="Painel, histórico e relatórios básicos no plano gratuito."),
dict(title="Pro: _R$ 19,90 por mês._", sub="Bot com IA no Telegram, várias contas, relatórios avançados e Excel."),
dict(title="Farmácia, mercado, _tudo no lugar._", msgs=[["u", "farmácia 38,90"], ["card", {"icon": "💊", "name": "Farmácia", "cat": "Saúde · Hoje", "amt": "38,90", "inc": False}]]),
dict(title="Venda algo? _Registre a entrada._", msgs=[["u", "vendi a bicicleta 450"], ["card", {"icon": "🚲", "name": "Venda da bicicleta", "cat": "Outras receitas · Hoje", "amt": "450,00", "inc": True}]]),
dict(title="O mês anterior _num comando._", msgs=[["u", "/saldo 09/2026"], ["wt", "📊 **Resumo de setembro**\nReceitas: R$ 6.800,00\nDespesas: R$ 3.240,00\nSaldo do mês: R$ 3.560,00"]]),
dict(title="Taxa de _poupança_ nos relatórios.", sub="Veja quanto da renda você está guardando."),
dict(title="Seu saldo _comparado_ com o mês passado.", img="dash-top"),
dict(title="Academia, streaming, _tudo registrado._", msgs=[["u", "academia 89,90"], ["card", {"icon": "🏋️", "name": "Academia", "cat": "Saúde · Hoje", "amt": "89,90", "inc": False}]]),
dict(title="Presente de aniversário? _Registrado._", msgs=[["u", "presente da Ana 120"], ["card", {"icon": "🎁", "name": "Presente da Ana", "cat": "Presentes · Hoje", "amt": "120,00", "inc": False}]]),
dict(title="Pet também _tem categoria._", msgs=[["u", "ração 145"], ["card", {"icon": "🐶", "name": "Ração", "cat": "Pet · Hoje", "amt": "145,00", "inc": False}]]),
dict(title="Gasolina? _Uma mensagem._", msgs=[["u", "gasolina 180"], ["card", {"icon": "⛽", "name": "Gasolina", "cat": "Transporte · Hoje", "amt": "180,00", "inc": False}]]),
]

# Datados (AAAA-MM-DD): substituem o bônus do dia
DATED = {
"2026-09-30": dict(t="tip", tag="Bem-vindo", title="O Wally chegou _no Instagram._", sub="Dicas de finanças e o app na prática, de segunda a sexta."),
"2026-10-12": dict(t="tip", tag="Dia das Crianças", title="Mesada é _aula de finanças._", sub="Feliz Dia das Crianças! 🧸"),
"2026-11-02": dict(t="tip", tag="Feriado", title="Feriado é dia de descansar, _e de registrar_ o que gastar.", sub=""),
"2026-11-20": dict(t="num", tag="Black Friday", big="1 semana", text="para a Black Friday. Já fez a lista do que precisa?", pre="Falta"),
"2026-11-23": dict(t="tip", tag="Black Friday", title="Anote _os preços de hoje._", sub="Na sexta, compare para ver se o desconto é real."),
"2026-11-26": dict(t="tip", tag="Black Friday", title="Amanhã é Black Friday.", sub="_Defina o teto_ antes de abrir os apps das lojas."),
"2026-11-27": dict(t="tip", tag="Black Friday", title="Comprou? _Registre agora._", sub="Assim o gasto não some no meio da fatura."),
"2026-11-30": dict(t="q", tag="Black Friday", title="O que você _comprou_ na Black Friday?", sub="Valeu a pena?"),
"2026-12-01": dict(t="tip", tag="Dezembro", title="Dezembro chegou.", sub="_Presentes, festas e 13º:_ um orçamento para cada um."),
"2026-12-24": dict(t="tip", tag="Feliz Natal", title="Boas festas! 🎄", sub="Que a ceia seja farta e a fatura, tranquila."),
"2026-12-31": dict(t="tip", tag="Réveillon", title="Tchau, 2026. 🥂", sub="Obrigado por estar com a gente. Até o ano que vem!"),
"2027-01-01": dict(t="q", tag="Feliz 2027", title="Qual é a sua _primeira meta_ de 2027?", sub=""),
"2027-01-04": dict(t="tip", tag="Janeiro", title="Primeira segunda do ano:", sub="_Registre os gastos de hoje._ Um dia de cada vez."),
"2027-02-09": dict(t="tip", tag="Carnaval", title="Carnaval é festa, _com teto de gastos._", sub="Aproveita! 🎭"),
"2027-03-15": dict(t="tip", tag="Dia do Consumidor", title="Promoção de hoje:", sub="_Estava na sua lista?_ Se não, espere 72h."),
"2027-04-30": dict(t="tip", tag="Imposto de Renda", title="Declarou o _Imposto de Renda?_", sub="Confira o prazo oficial no site da Receita Federal."),
"2027-05-24": dict(t="num", tag="Obrigado", big="100", text="posts no feed. Obrigado por acompanhar! 💙", pre=""),
"2027-06-11": dict(t="tip", tag="Dia dos Namorados", title="Amanhã é Dia dos Namorados. 💘", sub="Que tal criar _uma meta a dois?_"),
"2027-07-01": dict(t="tip", tag="Férias", title="Férias chegando.", sub="_Registre os gastos da viagem_ em tempo real pelo Telegram."),
"2027-09-07": dict(t="tip", tag="7 de Setembro", title="Independência financeira _é liberdade de escolha._", sub="Bom feriado! 🇧🇷"),
"2027-10-01": dict(t="tip", tag="Um ano", title="Um ano de _dinheiro organizado._", sub="Obrigado por estar com a gente. 💙"),
}
