"""Conteúdo novo dos stories bônus das 16h e 20h (não repete o de stories_content.py)."""

TIPS = [
("Olhe o extrato _uma vez por semana._", "Surpresa boa é só a de aniversário."),
("Troque o _“vou ver depois”_ por _“vou ver agora”._", "Conta esquecida vira multa."),
("Faça uma _lista de desejos._", "O que continuar nela depois de um mês, talvez valha a compra."),
("Não compre _para impressionar._", "Quem importa não está olhando a etiqueta."),
("Separe um valor para _manutenção da casa._", "Chuveiro, torneira e geladeira sempre quebram na pior hora."),
("Desligue o _cartão salvo_ nos apps de compra.", "Um passo a mais já freia o impulso."),
("Tire as _notificações de promoção_ do celular.", "Menos tentação, menos gasto."),
("Pergunte _“tem desconto no Pix?”_", "Muita loja dá, mas só se você perguntar."),
("Leve _garrafinha de água._", "Parece bobagem, mas soma no mês."),
("Planeje o _cardápio da semana._", "Menos desperdício e menos delivery."),
("Congele _porções_ de comida.", "O jantar pronto no freezer vence o aplicativo."),
("Use a _lista do mercado_ no celular.", "Ela vai com você sempre."),
("Vá ao mercado _uma vez por semana._", "Cada ida extra é uma chance de levar o que não precisa."),
("Confira a _data de validade_ das promoções.", "Leve só o que dá para usar a tempo."),
("Marca própria do mercado _vale o teste._", "Muitas têm qualidade parecida por menos."),
("Compre frutas e legumes _da estação._", "Costumam estar mais baratos e mais gostosos."),
("Não vá ao shopping _para passear._", "Passeio lá costuma terminar em sacola."),
("Venda o que está _parado em casa._", "Vira dinheiro e espaço."),
("Revise os _seguros duplicados._", "Às vezes o cartão já cobre o que você paga à parte."),
("Leia as _letras miúdas_ antes de assinar.", "Multa de cancelamento aparece lá."),
("Anote o _dia de renovação_ das assinaturas anuais.", "Cancelar depois costuma ser mais difícil."),
("Teste grátis? _Coloque um lembrete_ para cancelar.", "Antes da primeira cobrança."),
("Divida streaming _com a família._", "Muitos planos permitem mais de uma pessoa."),
("Revezar assinaturas _também funciona._", "Um mês uma, no outro mês outra."),
("Gasto com _aplicativo de transporte_ alto?", "Compare com ônibus, metrô ou carona."),
("Calibre os _pneus do carro._", "Pneu murcho aumenta o consumo de combustível."),
("Faça as _revisões do carro_ em dia.", "Manutenção barata evita conserto caro."),
("Pesquise o preço do _combustível_ no caminho.", "A diferença entre postos pode ser grande."),
("Guarde um pouco todo mês para _o IPVA._", "Janeiro agradece."),
("Evite _pagar juros_ de conta atrasada.", "Coloque as contas no débito automático ou num lembrete."),
("_Débito automático_ só para conta que você confere.", "Senão, erro de cobrança passa despercebido."),
("Tem dívida cara e dinheiro parado?", "_Quitar a dívida_ costuma render mais do que guardar."),
("Negocie _à vista_ dívidas antigas.", "Descontos grandes são comuns em renegociação."),
("Procure os _mutirões de renegociação._", "Muitas empresas dão condições especiais nessas épocas."),
("Antes de pegar empréstimo, _veja o CET._", "O Custo Efetivo Total mostra o preço real."),
("Troque dívida cara por _uma mais barata._", "Mas só se parar de fazer a cara."),
("Nunca pague para _“limpar o nome”_ com desconhecidos.", "Negocie direto com o credor."),
("Desconfie de _empréstimo fácil_ por mensagem.", "Quem cobra antes de liberar geralmente é golpe."),
("Nunca passe _código de verificação_ para ninguém.", "Nem para quem diz ser do banco."),
("Banco _não pede senha_ por telefone.", "Desligue e ligue você mesmo para o número oficial."),
("Confira o _nome do recebedor_ antes de mandar o Pix.", "Depois de enviado, é difícil voltar."),
("Ative os _limites do Pix_ no seu banco.", "Um teto noturno menor já protege bastante."),
("Pix agendado _também conta_ no orçamento.", "Registre quando programar."),
("Anote _para quem você emprestou._", "E quanto. A memória falha, o registro não."),
("Emprestou? _Combine a data_ de devolução.", "Fica mais fácil para os dois."),
("Divida a conta do bar _na hora._", "Depois ninguém lembra quem pediu o quê."),
("Vaquinha do presente? _Registre sua parte._", "Pequenos valores também são gasto."),
("Comeu fora? _Registre antes de sair_ do restaurante.", "Leva 5 segundos."),
("Viagem em grupo? _Combine o orçamento_ antes.", "Evita climão na hora de dividir."),
("Separe o dinheiro da _viagem_ do dia a dia.", "Assim você sabe o quanto ainda pode gastar lá."),
("Viajando? _Anote o câmbio_ de cada compra.", "O valor em reais é o que importa no fim."),
("Hospedagem com _cozinha_ ajuda a economizar.", "Nem toda refeição precisa ser em restaurante."),
("Leve _lanche_ para passeios e aeroporto.", "Preço de aeroporto assusta."),
("Mala leve, _menos taxa._", "Bagagem despachada custa caro em muitas companhias."),
("Pesquise passagens em _dias diferentes._", "Mudar um dia pode mudar o preço."),
("Casamento, formatura, festa?", "_Crie uma meta_ para cada evento do ano."),
("Anote _o gasto real_ das festas de fim de ano.", "No ano seguinte você planeja melhor."),
("Volta às aulas? _Reaproveite_ o material.", "Mochila e estojo podem durar mais de um ano."),
("Uniforme e livro _usados_ também servem.", "Grupos de pais costumam trocar."),
("Filho pedindo tudo?", "_Mostre o valor_ e deixe ele escolher dentro do limite."),
("Mesada com _metas_ ensina mais.", "Guardar para algo que ele quer é a melhor aula."),
("Ensine as crianças a _comparar preços._", "Vira brincadeira no mercado."),
("Aniversário infantil _não precisa de buffet._", "Criança lembra da diversão, não do salão."),
("Troque presentes por _experiências._", "Um passeio junto costuma marcar mais."),
("Amigo secreto? _Respeite o valor_ combinado.", "Nem para mais, nem para menos."),
("Compre presentes _ao longo do ano._", "Promoções aparecem fora de dezembro também."),
("Tenha _uma caixinha_ para gastos de fim de ano.", "Um pouco por mês desde janeiro."),
("Olhe a _conta de luz_ do mês passado.", "Subiu muito? Algo mudou em casa."),
("Banho mais curto _também é economia._", "Chuveiro elétrico pesa na conta."),
("Tire da tomada _o que não usa._", "Carregador ligado sem celular também gasta."),
("Lâmpada LED _compensa._", "Gasta menos e dura mais."),
("Junte roupa para _encher a máquina._", "Menos lavagens, menos água e luz."),
("Geladeira aberta _gasta energia._", "Decida o que vai pegar antes de abrir."),
("Conta de água alta?", "_Procure vazamentos._ Uma descarga pingando desperdiça muito."),
("Revise o _plano do celular._", "Você usa todos os gigas que paga?"),
("Pergunte na operadora por _planos novos._", "Cliente antigo às vezes paga mais caro."),
("Sua internet é _maior do que precisa?_", "Nem toda casa precisa da velocidade máxima."),
("Tem _TV por assinatura_ e streaming?", "Talvez um dos dois já baste."),
("Academia que você não vai?", "_Cancele_ ou troque por um plano mais barato."),
("Exercício ao ar livre _não custa nada._", "Caminhada, corrida, parque."),
("Remédio de uso contínuo?", "_Compare farmácias_ e programas de desconto."),
("Pergunte pelo _genérico._", "Mesmo princípio ativo, preço menor."),
("Cuide da saúde _hoje._", "Prevenção custa menos do que tratamento."),
("Tenha _uma reserva para saúde_ mesmo com plano.", "Coparticipação e remédios aparecem."),
("Pet? _Guarde um pouco_ para o veterinário.", "Emergência de pet também acontece."),
("Ração em _embalagem maior_ pode valer a pena.", "Faça a conta do preço por quilo."),
("Salão, barbearia, unha?", "_Anote o gasto mensal._ Pode surpreender."),
("Roupa nova? _Tire uma antiga_ do armário.", "Ajuda a perceber quanto você já tem."),
("Compre roupa _pelo uso_, não pela promoção.", "A peça que fica na gaveta custa caro."),
("Conserte antes de _trocar._", "Costureira e sapateiro existem por um motivo."),
("Brechó _também é moda._", "E cabe no bolso."),
("Eletrônico novo? _Espere o lançamento_ do próximo.", "O modelo anterior costuma baixar de preço."),
("Garantia estendida _nem sempre vale._", "Faça as contas antes de aceitar."),
("Guarde a _nota fiscal._", "Sem ela, a garantia fica difícil."),
("Comprou com defeito? _Você tem direitos._", "Procure o Código de Defesa do Consumidor."),
("Compra online? _Confira a reputação_ da loja.", "Preço bom demais pode ser golpe."),
("Link de promoção no WhatsApp?", "_Digite o site você mesmo._ Não clique."),
("Frete caro? _Retire na loja_ se puder.", "Muitas lojas oferecem essa opção sem custo."),
("Junte compras online _num pedido só._", "Menos fretes, menos gasto."),
("Cupom de desconto _só vale_ se a compra já estava planejada.", ""),
("Desinstale o app da loja _que mais te tenta._", "Dá para comprar pelo site quando precisar."),
("Crie uma _pausa_ antes de finalizar a compra.", "Feche o app e volte em uma hora."),
("Compre _pensando no mês que vem._", "A fatura chega depois, mas chega."),
("Some as _parcelas em aberto._", "Esse número mostra quanto do futuro já está gasto."),
("Evite parcelar _coisas pequenas._", "Várias parcelinhas viram um peso grande."),
("Tenha _um cartão principal._", "Fica mais fácil acompanhar."),
("Anuidade? _Peça isenção_ ao banco.", "Muitos bancos aceitam negociar."),
("Use o _aplicativo do banco_ para travar o cartão.", "Perdeu? Bloqueie na hora."),
("Cartão virtual para _compras online._", "Mais segurança se o site for invadido."),
("Pagou a fatura? _Confira se caiu._", "Evita juros por erro de pagamento."),
("Não pague a fatura _no último minuto._", "Imprevisto no dia pode virar juros."),
("Recebe _dia 5?_", "Coloque os vencimentos logo depois dessa data."),
("Pode escolher o vencimento?", "_Escolha perto do salário._"),
("Primeiro emprego?", "_Comece a guardar_ desde o primeiro salário."),
("Aumento de salário?", "_Aumente o valor guardado_ antes de aumentar os gastos."),
("Mudou de emprego? _Revise o orçamento._", "Benefícios diferentes mudam as contas."),
("Vale-refeição sobrando ou faltando?", "_Planeje as refeições_ pelo valor do mês."),
("Autônomo? _Separe o imposto_ assim que receber.", "Esse dinheiro não é seu para gastar."),
("MEI? _Pague o DAS em dia._", "Atraso gera multa e juros."),
("Renda extra? _Registre como receita._", "Assim você sabe o quanto ela realmente ajuda."),
("Freela pago? _Separe uma parte_ para a reserva.", "Renda variável pede colchão maior."),
("Mês bom? _Guarde para o mês fraco._", "Renda variável é assim mesmo."),
("Defina _um salário para você_ mesmo sendo autônomo.", "O resto fica na conta do negócio."),
("Planeje a _aposentadoria cedo._", "Quanto antes começa, menos precisa guardar por mês."),
("Conheça seu _custo de vida._", "É o número mais importante das suas finanças."),
("Calcule _quanto custa um mês seu._", "Some aluguel, contas, mercado, transporte e o resto."),
("Reserva de emergência _primeiro._", "Depois as outras metas."),
("Guarde a reserva onde tenha _liquidez._", "Precisa poder sacar rápido."),
("Rendimento da reserva _não é o foco._", "Segurança e acesso rápido vêm antes."),
("Antes de investir, _entenda o produto._", "Se não entende, não compre."),
("Promessa de _retorno garantido alto?_", "Desconfie. Pode ser pirâmide."),
("Investimento _com prazo_ para uma meta com prazo.", "Casar os dois evita resgatar antes da hora."),
("Diversificar _é não depender_ de uma coisa só.", "Vale para investimentos e para renda."),
("Taxa de administração _importa._", "Taxas altas comem o rendimento com o tempo."),
("Investir pouco _é melhor_ do que não investir.", "O hábito vem antes do valor."),
("Não tome decisão financeira _com raiva._", "Espere a cabeça esfriar."),
("Não tome decisão financeira _com pressa._", "Quem apressa geralmente quer vender."),
("Comprou algo caro? _Espere antes_ de comprar outro.", "Deixe o orçamento respirar."),
("Seu padrão de vida _cresceu junto_ com o salário?", "Vale olhar se faz sentido."),
("Compare-se com _você do mês passado._", "Não com o perfil dos outros."),
("Rede social _não mostra a fatura._", "A vida real dos outros também tem boleto."),
("Diga _não_ para convites caros sem culpa.", "Proponha algo que caiba no bolso."),
("Encontro com amigos _em casa_ também é bom.", "Cada um leva um prato."),
("Lazer grátis _existe._", "Parques, museus em dias gratuitos, eventos na rua."),
("Biblioteca _ainda existe._", "E livro emprestado é de graça."),
("Hobby barato _também relaxa._", "Caminhar, desenhar, cozinhar."),
("Recompense-se _dentro do plano._", "Premiar é bom, estourar o orçamento não."),
("Separe um valor para _você mesmo_ todo mês.", "Quem nunca gasta com si mesmo acaba desistindo."),
("Revise o _orçamento de lazer_ se sempre estoura.", "Talvez o valor planejado esteja irreal."),
("Orçamento _realista_ dura mais.", "Apertado demais quebra no segundo mês."),
("Estourou uma categoria?", "_Tire de outra_ em vez de desistir de tudo."),
("Errou no mês? _Recomeça no próximo._", "Um mês ruim não apaga o progresso."),
("Não espere a _segunda-feira_ para começar.", "Registre o próximo gasto, qualquer dia."),
("Não espere _ganhar mais_ para organizar.", "Organizar é o que faz o dinheiro render."),
("Revise os gastos _com o parceiro._", "Uma conversa por mês já ajuda muito."),
("Metas _a dois_ unem mais do que dividem.", "Viagem, casa, casamento."),
("Contas da casa? _Combinem a divisão._", "Proporcional à renda é uma opção justa."),
("Cada um com _um pouco de liberdade._", "Um valor livre para cada um evita briga."),
("Mudando de casa? _Some os custos escondidos._", "Mudança, caução, móveis, contas iniciais."),
("Aluguel ideal? Uma parte _que caiba_ no orçamento.", "Moradia cara aperta todas as outras contas."),
("Condomínio e IPTU _entram na conta_ da moradia.", "Não só o aluguel."),
("Vai comprar imóvel? _Guarde a entrada._", "E some documentação e mudança."),
("Financiamento longo _paga muito juro._", "Amortizar quando puder reduz o total."),
("Carro novo? _Some os custos anuais._", "Seguro, IPVA, manutenção, combustível."),
("Pense no _custo total_, não só na parcela.", "Parcela que cabe pode esconder um total alto."),
("Reforma? _Orce com folga._", "Obra quase sempre custa mais do que o planejado."),
("Peça _3 orçamentos_ de qualquer serviço.", "Pintor, mecânico, eletricista."),
("Pague serviço _depois de pronto_ quando possível.", "Ou em etapas combinadas."),
("Doação _também entra_ no orçamento.", "Planejar ajuda a doar com regularidade."),
("Tenha uma _pasta com documentos_ importantes.", "Contratos, apólices, notas."),
("Senhas de banco? _Nunca anote no celular_ em texto aberto.", "Use um gerenciador de senhas."),
("Celular roubado? _Bloqueie os bancos_ logo.", "Tenha os números das centrais anotados."),
("Revise quem tem _acesso às suas contas._", "Apps conectados, cartões salvos, dispositivos."),
("Organizar começa com _uma pergunta:_", "Para onde foi o meu dinheiro?"),
("Anotar é _o primeiro passo._", "Decidir vem depois."),
("Fim do dia? _Confira se registrou tudo._", "Um minuto antes de dormir."),
("Domingo à noite _é um bom momento._", "Revise a semana e planeje a próxima."),
("Primeiro dia do mês?", "_Defina o orçamento_ antes de gastar."),
("Último dia do mês?", "_Veja o que sobrou_ e mande para uma meta."),
("Todo dia 15, _olhe o orçamento._", "Metade do mês, metade do caminho."),
("Aprenda _uma coisa nova_ de finanças por mês.", "Conhecimento também é investimento."),
("Dinheiro _não aceita desaforo._", "Nem esquecimento."),
("Planejar _não é deixar de viver._", "É viver sem susto."),
("O que não é medido _não é controlado._", "Registre para enxergar."),
("Pequenas vitórias _contam._", "Comemore cada mês no azul."),
("Constância _vence intensidade._", "Um pouco todo dia vale mais do que muito uma vez."),
("Sua relação com dinheiro _pode mudar._", "Começa com um hábito pequeno."),
("Ninguém nasce _sabendo organizar._", "Se aprende fazendo."),
("Hoje é um bom dia para _registrar um gasto._", "O de agora mesmo."),
("Tenha _um número_ para cada meta.", "“Guardar mais” não se mede. “R$ 5 mil” sim."),
("Faça _depósitos automáticos_ para a meta.", "Programe no dia do salário."),
("Troque _refrigerante por água_ no restaurante.", "A conta fica mais leve."),
("Faça café _em casa._", "E leve na garrafinha térmica."),
("Aproveite o _dia de preço baixo_ do mercado.", "Muitos têm dia de promoção de hortifrúti."),
("Compre _pão do dia_ na medida.", "Pão que sobra vira desperdício."),
("Faça _inventário da despensa_ antes do mercado.", "Evita comprar o que já tem."),
("Receita com _o que tem em casa._", "Antes de pedir, abra a geladeira."),
("Pesquise _programas de fidelidade_ que você já usa.", "Mas não gaste para ganhar pontos."),
("Cancele _cartões que não usa._", "Menos risco de cobrança esquecida."),
("Leia a fatura _no dia que fecha._", "Dá tempo de contestar antes de pagar."),
("Some quanto você paga de _tarifas_ por ano.", "Pode dar para trocar de banco."),
("Organize as metas por _prioridade._", "A primeira recebe mais."),
("Anote _o motivo_ de cada compra grande.", "Ajuda a entender seus padrões."),
("Na dúvida entre dois produtos?", "_Leve nenhum_ e pense em casa."),
("Tenha _um dia sem compras_ por semana.", "Nem online, nem na rua."),
("Revise os _presentes do ano_ em janeiro.", "Anote as datas no calendário."),
("Compre ingresso _antecipado._", "Lote promocional costuma ser mais barato."),
("Dinheiro de presente?", "_Coloque numa meta_ que você queria."),
("Organize-se _do seu jeito._", "O importante é começar e manter."),
]

LEMBRETES = [
("Já registrou _o almoço_ de hoje?", ""),
("Já registrou _o café_ de hoje?", ""),
("Pagou algo hoje?", "_Registra agora_ antes de esquecer."),
("Uma mensagem, _um gasto registrado._", "Simples assim."),
("Como está _o orçamento_ da semana?", "Dá uma olhada rápida."),
("Hoje tem _conta vencendo?_", "Confere os vencimentos."),
("Recebeu algo hoje?", "_Registre a entrada_ também."),
("Seu futuro _começa no gasto de hoje._", ""),
("Fim de expediente.", "_Um minuto_ para registrar o dia."),
("Sexta-feira chegou.", "_Defina o teto_ do fim de semana."),
("Segunda-feira, _semana nova._", "Qual é o limite livre desta semana?"),
("Quarta-feira: _metade da semana._", "Como estão os gastos até aqui?"),
("Quinta-feira, _quase lá._", "Já pensou no orçamento do fim de semana?"),
("Terça-feira é dia de _conferir o saldo._", "Dois minutos e pronto."),
("Antes de dormir:", "_Registrou tudo_ o que gastou hoje?"),
("Pequeno gasto _também conta._", "Anotou o de hoje?"),
("Lembrete amigo:", "_Anote o Uber_ de hoje."),
("Lembrete amigo:", "_Anote o mercado_ de hoje."),
("Lembrete amigo:", "_Anote o delivery_ de hoje."),
("Olhou suas _metas_ esta semana?", "Elas estão te esperando."),
("Depositou algo _numa meta_ este mês?", "Qualquer valor conta."),
("Seu mês está _no azul?_", "Confere no painel."),
("Hoje é dia de _não gastar_ com nada extra?", "Tenta e vê como é."),
("Deu vontade de comprar?", "_Respira._ Amanhã você decide."),
("Seu eu de amanhã", "_agradece_ o registro de hoje."),
("Uma ação por dia:", "_registrar._"),
("Controle bom é _controle leve._", "Uma mensagem de cada vez."),
("Cada gasto registrado", "_é um pedaço_ do quebra-cabeça."),
("Você no controle,", "_não a fatura._"),
("Boa noite! 🌙", "_Registrou_ os gastos do dia?"),
("Bom descanso. 🌙", "Amanhã é _mais um dia_ de dinheiro organizado."),
("Tarde de _foco nas contas?_", "Uma olhadinha rápida no painel."),
("Gastou no happy hour?", "_Registra antes_ de ir embora."),
("Fez compra por impulso hoje?", "_Tudo bem._ Registre e siga."),
("Semana corrida?", "_Registrar leva 5 segundos._"),
("Hoje o dia foi _econômico?_", "Conta pra gente."),
("Qual foi o _último gasto_ que você registrou?", ""),
("Uma meta _perto de bater?_", "Falta pouco. Continua!"),
("Mês quase no fim.", "_Como está o saldo?_"),
("Começo de mês:", "_hora de planejar._"),
("Salário caiu?", "_Guarde primeiro,_ gaste depois."),
("Já separou o valor _da reserva_ este mês?", ""),
("Está com _fatura alta?_", "Veja quais parcelas terminam logo."),
("Gastou com presente?", "_Categoria Presentes_ nele."),
("Encheu o tanque?", "_Registra a gasolina._"),
("Farmácia hoje?", "_Anota o valor._"),
("Foi ao mercado?", "_Uma mensagem_ e está registrado."),
("Pediu comida hoje?", "_O delivery também entra._"),
("Pagou uma conta?", "_Registre para acompanhar_ o mês."),
("Um gasto por vez,", "_um mês organizado._"),
]

QUESTIONS = [
("Você sabe _quanto gastou_ ontem?", "Sem olhar o extrato!"),
("Qual _conta fixa_ mais pesa no seu mês?", ""),
("Você já fez uma _semana sem gastos extras?_", "Conta como foi."),
("Você tem uma _caixinha para presentes?_", ""),
("Quantas _assinaturas_ você tem hoje?", "Conta nos dedos."),
("Você anota os gastos _na hora_ ou _no fim do dia?_", ""),
("Qual foi a _compra mais inútil_ que você já fez?", "Todo mundo tem uma. 😅"),
("Você já tentou o _método 50·30·20?_", "Funcionou?"),
("Você prefere _cartão_ ou _Pix_ no dia a dia?", ""),
("Qual é o seu _sonho de consumo_ para este ano?", ""),
("Você já _renegociou uma dívida?_", "Deu certo?"),
("Você sabe quanto _custa um mês_ da sua vida?", ""),
("Você tem _meta de aposentadoria?_", "Ou ainda nem pensou nisso?"),
("Qual o seu _maior gasto_ com lazer?", ""),
("Você já pagou _juros do rotativo?_", "Sem vergonha, é mais comum do que parece."),
("Qual é o gasto que você _nunca corta?_", "Aquele que vale cada centavo."),
("Você faz _lista de mercado?_", "E segue ela?"),
("Você conversa sobre dinheiro com _os amigos?_", ""),
("Quem cuida das _finanças_ na sua casa?", ""),
("Você já _economizou_ para uma viagem?", "Para onde foi?"),
("Você tem _investimentos?_", "Ou ainda está na reserva?"),
("Qual _hábito_ te ajudou a gastar menos?", ""),
("Você já foi vítima de _golpe financeiro?_", "Compartilhar ajuda outras pessoas."),
("Qual _desafio financeiro_ você toparia?", "Semana sem delivery? 30 dias anotando tudo?"),
("Você revisa os _débitos automáticos?_", ""),
("Quanto tempo você leva para _registrar um gasto?_", ""),
("Você usa _cashback?_", "Ele te faz gastar mais ou menos?"),
("O que você faria com o _13º?_", ""),
("Você comemora quando _bate uma meta?_", "Como?"),
("Qual conselho de dinheiro você daria ao seu _eu de 18 anos?_", ""),
("Você tem _renda extra?_", "Qual?"),
("Você já vendeu algo _usado_ na internet?", "Como foi?"),
("Você prefere _economizar em várias coisas_ ou _cortar uma grande?_", ""),
("Qual _categoria_ mais te surpreendeu quando começou a anotar?", ""),
("Seu salário cai em _qual dia?_", "E as contas vencem quando?"),
("Você já esqueceu de _cancelar um teste grátis?_", "Quanto custou? 😅"),
("Você planeja os _presentes de Natal_ com antecedência?", ""),
("Qual é a sua _maior dúvida_ sobre investimentos?", ""),
("Você tem _dívida_ hoje?", "Conta pra gente como está lidando."),
("Qual foi o melhor _conselho financeiro_ que você recebeu?", ""),
("Você acha que gasta mais no _fim de semana?_", ""),
("Você tem uma _meta com data?_", "Qual?"),
("Qual o _valor máximo_ que você gasta sem pensar duas vezes?", ""),
("Você prefere _poupar para comprar_ ou _parcelar?_", ""),
("Você usa _alguma ferramenta_ para organizar o dinheiro?", "Planilha, caderno, app?"),
("Qual _conta_ você mais esquece de pagar?", ""),
("Você já ajudou alguém a _organizar as finanças?_", ""),
("Você fala de dinheiro com _seus filhos?_", ""),
("Quanto você gasta com _café_ por mês?", "Chuta."),
("Qual gasto _você esconde de si mesmo?_", "Aquele que você finge que não viu."),
("Você já fez _orçamento de viagem?_", "Bateu com o real?"),
("O que te _impede_ de guardar dinheiro hoje?", ""),
("Qual _mania_ te faz gastar?", "Promoção, tédio, rede social…"),
("Você já comprou algo porque _todo mundo tinha?_", ""),
("Qual _serviço_ você pagaria com prazer mesmo apertando?", ""),
("Você olha o _saldo_ todo dia?", "Ou evita?"),
("Você prefere metas _pequenas e rápidas_ ou _grandes e longas?_", ""),
("Qual é o seu _gasto mais recorrente?_", ""),
("Você já teve _mês no vermelho?_", "Como saiu dele?"),
("O que significa _liberdade financeira_ para você?", ""),
("Você tem _algum ritual_ de começo de mês?", ""),
("Você lembraria de _todos os gastos_ desta semana?", "Tenta listar."),
("Qual foi a _economia_ que mais te orgulhou?", ""),
("Você usa o _limite do cheque especial?_", ""),
("Quanto você acha que gasta com _transporte?_", ""),
("Você acompanha a _conta de luz?_", "Ela subiu ou desceu este ano?"),
("Qual o seu _próximo passo_ nas finanças?", ""),
("Você faz _compras no mercado_ semanais ou mensais?", ""),
("Se pudesse cortar _uma conta fixa_, qual seria?", ""),
("Você acredita que dá para _guardar ganhando pouco?_", "Conta sua experiência."),
]

NUMS = [
("R$ 8", "de café por dia útil viram cerca de **R$ 176** por mês.", ""),
("R$ 50", "por semana guardados viram **R$ 2.600** em um ano.", ""),
("R$ 2 por dia", "viram **R$ 730** no ano.", "Só"),
("R$ 30", "de aplicativo de transporte 2x por semana somam **R$ 240** por mês.", ""),
("4", "assinaturas de R$ 30 são **R$ 1.440** por ano.", ""),
("R$ 200", "a menos por mês no mercado são **R$ 2.400** no ano.", ""),
("R$ 10", "por dia de lanche no trabalho são cerca de **R$ 220** por mês.", ""),
("1 hora", "por mês para revisar as finanças. É menos do que um episódio de série.", ""),
("R$ 300", "por mês por 12 meses: **R$ 3.600** para aquela viagem.", ""),
("24h", "de espera antes de comprar já derrubam muito impulso.", ""),
("10x de R$ 99", "são **R$ 990**. Olhe sempre o total.", ""),
("R$ 150", "por mês guardados para o IPVA cobrem **R$ 1.800** em janeiro.", ""),
("R$ 1.000", "de fatura em 5 parcelas ainda são **R$ 1.000**.", ""),
("R$ 20", "por semana guardados viram **R$ 1.040** no ano.", ""),
("3", "perguntas antes de comprar: preciso? cabe? é o melhor preço?", ""),
("R$ 45", "de pizza toda sexta são **R$ 2.340** no ano.", ""),
("5%", "da renda já é um começo para quem nunca guardou.", ""),
("R$ 12", "de estacionamento 3x por semana passam de **R$ 150** por mês.", ""),
("2 minutos", "por dia bastam para manter os gastos em dia.", ""),
("R$ 60", "por mês de streaming são **R$ 720** por ano.", ""),
("R$ 500", "de reserva já seguram muitos imprevistos pequenos.", "Até"),
("R$ 80", "de cabeleireiro por mês são **R$ 960** por ano.", ""),
("12", "meses no ano. Dá para dividir qualquer gasto anual por eles.", ""),
("R$ 5 por dia", "são **R$ 150** por mês. E **R$ 1.825** no ano.", ""),
("R$ 3.000", "de meta ÷ 10 meses = **R$ 300** por mês.", ""),
("R$ 250", "por mês guardados viram **R$ 3.000** no ano, sem contar rendimento.", ""),
("1 lista", "de mercado pode poupar várias idas extras.", ""),
("6", "meses de custo de vida é uma reserva mais tranquila para renda variável.", "Pelo menos"),
("R$ 35", "de delivery 2x por semana são mais de **R$ 3.600** por ano.", ""),
("R$ 900", "de presentes em dezembro? São **R$ 75** por mês desde janeiro.", ""),
("R$ 15", "de taxa de entrega 8x por mês são **R$ 120**.", ""),
("0", "é o valor de um mês sem juros no cartão. Pague a fatura inteira.", ""),
("R$ 400", "de gasto com carro por mês são **R$ 4.800** no ano.", ""),
("R$ 7", "por dia de refrigerante e doce viram **R$ 210** no mês.", ""),
("R$ 100", "a menos no lazer por mês bancam **R$ 1.200** de viagem.", ""),
("R$ 1.200", "de viagem? São **R$ 100** por mês durante um ano.", ""),
("R$ 25", "de assinatura esquecida por 2 anos: **R$ 600**.", ""),
("R$ 40", "de bar toda semana são **R$ 2.080** no ano.", ""),
("R$ 1", "por dia no cofrinho viram **R$ 365** no ano.", ""),
("R$ 180", "de gasolina por semana são **R$ 720** por mês.", ""),
("R$ 2.000", "de celular em 10x: **R$ 200** por mês por quase um ano.", ""),
("R$ 70", "a menos no plano de celular e internet: **R$ 840** por ano.", ""),
("R$ 120", "de academia sem ir 6 meses: **R$ 720** perdidos.", ""),
("R$ 350", "de mercado por semana são **R$ 1.400** por mês.", ""),
("21 dias", "anotando todos os gastos ajudam a criar o hábito.", ""),
("R$ 600", "de reserva para o carro cobrem uma boa revisão.", ""),
("R$ 9,90", "de app por mês parece pouco. São **R$ 118,80** no ano.", ""),
("R$ 18", "de lanche no fim do expediente 4x por semana: **R$ 288** por mês.", ""),
("R$ 50", "de uma venda de usado. Direto para a meta.", ""),
("R$ 10.000", "de meta ÷ 24 meses ≈ **R$ 417** por mês.", ""),
]

MITOS = [
("Só vou organizar quando ganhar mais.", "Organizar é o que **faz sobrar**, mesmo ganhando pouco."),
("Fatura alta é sinal de muita compra grande.", "Muitas vezes são **várias pequenas** somadas."),
("Débito automático resolve tudo.", "Resolve o esquecimento, mas **você ainda precisa conferir.**"),
("Poupar é para o futuro distante.", "É também para **a viagem do ano que vem.**"),
("Dinheiro guardado é dinheiro parado.", "Guardado com destino **está trabalhando para você.**"),
("Só quem tem dívida precisa de controle.", "Controle é o que **evita** a dívida."),
("Pagar o mínimo da fatura resolve.", "O resto vira **rotativo**, um dos créditos mais caros."),
("Mais cartões, mais limite, mais tranquilidade.", "Mais cartões, **mais faturas** para controlar."),
("Parcelar tudo ajuda o orçamento.", "Parcelas acumuladas **prendem** os próximos meses."),
("Investir é só para especialista.", "Dá para **começar simples** e aprender no caminho."),
("Planejar tira a graça de gastar.", "Gastar sabendo que cabe **é muito melhor.**"),
("Não vale a pena anotar gastos pequenos.", "São eles que **mais escapam** no fim do mês."),
("Salário alto resolve problema de dinheiro.", "Sem controle, **o gasto cresce junto.**"),
("Controlar gasto é coisa de pão-duro.", "É coisa de quem **escolhe** onde gastar."),
("Reserva de emergência pode ficar em qualquer lugar.", "Precisa de **segurança e resgate rápido.**"),
("Juro baixo é juro bom.", "Qualquer juro **pesa** se a dívida for longa."),
("Empréstimo resolve aperto.", "Sem mudar o orçamento, **o aperto volta** com parcela."),
("Não dá para economizar no mercado.", "Lista, comparação e marca própria **fazem diferença.**"),
("Cashback é dinheiro de graça.", "Só se você **não gastou a mais** para ganhar."),
("Casal tem que juntar todo o dinheiro.", "Cada casal **combina o seu jeito.** O importante é conversar."),
("Criança não precisa aprender sobre dinheiro.", "Quanto **mais cedo**, mais natural fica."),
("Um mês ruim estraga tudo.", "Um mês ruim é **só um mês.** Recomeça no próximo."),
("Controle financeiro exige horas por semana.", "Registrar na hora leva **segundos.**"),
("Autônomo não consegue se organizar.", "Consegue, com **salário fixo para si** e reserva maior."),
("Só grandes gastos fazem diferença.", "Pequenos gastos **diários** somam muito no ano."),
("Pix é mais seguro do que cartão sempre.", "Cada um tem riscos. **Confira sempre** o recebedor."),
("Promoção relâmpago é oportunidade única.", "Promoção **volta.** Pressa é estratégia de venda."),
("Conta digital não é confiável.", "Muitas são **reguladas pelo Banco Central.** Pesquise antes."),
("Seguro é dinheiro jogado fora.", "Seguro certo **protege** de um prejuízo grande."),
("Só se aposenta bem quem tem muito dinheiro.", "Quem **começa cedo** precisa de menos por mês."),
("Imprevisto não dá para prever.", "O quê, não. Mas **que vai acontecer**, sim. Por isso a reserva."),
("Gastar com lazer é desperdício.", "Lazer **planejado** faz parte de uma vida saudável."),
("Mercado grande é sempre mais barato.", "**Compare.** Às vezes o do bairro ganha."),
("Comprar à vista é sempre melhor.", "Só se o dinheiro **não fizer falta** para a reserva."),
("Estou velho demais para começar a guardar.", "O melhor momento **é agora.**"),
("Estou novo demais para pensar nisso.", "O tempo **é o seu maior aliado.**"),
("Quem controla gasto não se diverte.", "Quem controla **se diverte sem culpa.**"),
("Não tenho gastos supérfluos.", "Anote por um mês. **Às vezes aparecem.**"),
("Saldo positivo significa que está tudo bem.", "Olhe também as **parcelas futuras** e as metas."),
("App de finanças precisa acessar meu banco.", "No Wally, **você registra** o que quiser, sem conectar conta."),
("Dinheiro não traz felicidade, então tanto faz.", "Mas **falta de dinheiro** traz preocupação."),
("Organizar finanças é só cortar gastos.", "É também **aumentar a renda** e definir metas."),
("Taxa pequena não faz diferença.", "Com o tempo, **faz e muito.**"),
("Guardar o que sobra funciona.", "Quase nunca sobra. **Guarde primeiro.**"),
("Uma planilha perfeita resolve.", "O que resolve é **o hábito**, não a ferramenta."),
]

LISTS = [
("Antes de _assinar algo_", "Assinaturas", ["Vou usar todo mês?", "Tem período grátis?", "Como cancelo?"]),
("Para _economizar em casa_", "Casa", ["Luz: banhos curtos", "Água: conferir vazamentos", "Gás: panela tampada"]),
("Antes de _viajar_", "Viagem", ["Orçamento total", "Reserva para imprevisto", "Registro dos gastos"]),
("Na _viagem_", "Viagem", ["Anote cada gasto", "Compare câmbios", "Leve lanche"]),
("Ao _receber o salário_", "Rotina", ["Guarde a meta", "Pague as fixas", "Veja o valor livre"]),
("Para evitar _golpes no Pix_", "Segurança", ["Confira o nome", "Desconfie de urgência", "Ligue para confirmar"]),
("Ao _renegociar dívida_", "Dívidas", ["Peça desconto à vista", "Veja o total", "Guarde o acordo"]),
("Para o _fim de semana_", "Planejamento", ["Teto de gastos", "Programa barato", "Registrar no domingo"]),
("Sinais de que _o orçamento aperta_", "Alerta", ["Cheque especial", "Fatura crescendo", "Nada guardado"]),
("Para _quitar o cartão_", "Cartão", ["Pare de usar", "Liste as parcelas", "Negocie o saldo"]),
("Na hora de _comprar um carro_", "Carro", ["Seguro", "IPVA", "Manutenção"]),
("Custos de _ter um pet_", "Pet", ["Ração", "Veterinário", "Banho e tosa"]),
("Para _o primeiro salário_", "Começo", ["Guarde uma parte", "Evite parcelar", "Anote tudo"]),
("Ao _mudar de casa_", "Moradia", ["Caução", "Mudança", "Contas iniciais"]),
("Para o _Natal_", "Presentes", ["Lista de pessoas", "Valor para cada uma", "Comprar antes de dezembro"]),
("Para o _começo do ano_", "Janeiro", ["Separar IPVA e IPTU", "Revisar metas", "Material escolar"]),
("Organizando _as assinaturas_", "Assinaturas", ["Liste todas", "Marque as que usa", "Cancele o resto"]),
("Para _economizar no delivery_", "Alimentação", ["Cozinhe no domingo", "Limite semanal", "Retire no local"]),
("Para _não esquecer contas_", "Contas", ["Lembretes", "Datas próximas", "Débito com conferência"]),
("Ao pegar _um empréstimo_", "Crédito", ["Veja o CET", "Compare 3 opções", "Some o total"]),
("Para _começar a investir_", "Investimentos", ["Reserva pronta", "Objetivo definido", "Entenda o produto"]),
("Reserva de emergência _ideal_", "Reserva", ["Segura", "Resgate rápido", "Separada do dia a dia"]),
("Gastos que _parecem pequenos_", "Gastos", ["Café", "Taxa de entrega", "Estacionamento"]),
("Para _renda extra_", "Renda", ["Venda o que não usa", "Freelas", "Um hobby que paga"]),
("Para o _casal organizar_", "Finanças a dois", ["Conta conjunta ou não", "Metas comuns", "Valor livre para cada um"]),
("Ensinando _crianças_", "Família", ["Mesada", "Cofrinho com meta", "Comparar preços juntos"]),
("Antes da _Black Friday_", "Consumo", ["Lista do que precisa", "Preço de hoje anotado", "Teto de gastos"]),
("Para _pagar menos juros_", "Juros", ["Fatura inteira", "Evite cheque especial", "Contas em dia"]),
("Seu _painel mensal_", "Rotina", ["Receitas", "Despesas", "Saldo"]),
("3 _metas_ para todo mundo", "Metas", ["Reserva", "Algo que você quer", "Futuro"]),
("Para _revisar o mês_", "Revisão", ["Maior categoria", "Maior surpresa", "O que ajustar"]),
("Antes de _emprestar dinheiro_", "Relações", ["Posso perder esse valor?", "Qual o prazo?", "Anote tudo"]),
("Para _economizar na farmácia_", "Saúde", ["Genérico", "Programas de desconto", "Compare preços"]),
("Contas que _dá para negociar_", "Negociação", ["Internet", "Celular", "Seguros"]),
("Para _o feriado_", "Feriado", ["Orçamento", "Passeio grátis", "Registrar no dia"]),
("Hábitos de quem _tem reserva_", "Hábitos", ["Guarda primeiro", "Anota tudo", "Planeja o ano"]),
("Para _o 13º_", "13º salário", ["Dívidas caras", "Reserva", "Algo planejado"]),
("Para _a restituição do IR_", "Imposto de Renda", ["Quitar dívidas", "Reforçar a reserva", "Meta pendente"]),
("Na hora de _comprar online_", "Compras", ["Loja confiável", "Frete incluso na conta", "Prazo de troca"]),
("Para _organizar documentos_", "Organização", ["Notas fiscais", "Contratos", "Comprovantes de saúde"]),
("Se _o dinheiro acabou_ antes do mês", "Alerta", ["Veja onde foi", "Corte o extra", "Planeje o próximo"]),
("Quando _perder o emprego_", "Imprevistos", ["Use a reserva com calma", "Corte o não essencial", "Revise contas fixas"]),
("Para _o aniversário_", "Festas", ["Defina o teto", "Lista de convidados", "Faça em casa"]),
("Para _o Dia das Mães e dos Pais_", "Presentes", ["Valor combinado", "Algo feito por você", "Experiência juntos"]),
("Custos _escondidos_ do carro", "Carro", ["Estacionamento", "Pedágio", "Multas"]),
("Rotina _semanal_ de 10 minutos", "Hábitos", ["Registrar o que faltou", "Olhar o orçamento", "Planejar a semana"]),
("Antes de _trocar de celular_", "Consumo", ["O meu ainda funciona?", "Vender o antigo", "Esperar promoção real"]),
("Para _sair do cheque especial_", "Dívidas", ["Pare de usar", "Troque por crédito mais barato", "Quite o quanto antes"]),
("Para _a primeira meta_ no Wally", "Metas", ["Nome", "Valor", "Primeiro depósito"]),
("Para _fechar o ano_ bem", "Dezembro", ["Revisar metas", "Somar o que guardou", "Planejar o próximo"]),
]

APP = [
dict(title="Almoço? _Uma mensagem._", msgs=[["u", "almoço 32,90"], ["card", {"icon": "🍽️", "name": "Almoço", "cat": "Alimentação · Hoje", "amt": "32,90", "inc": False}]]),
dict(title="Padaria _registrada._", msgs=[["u", "padaria 18,50"], ["card", {"icon": "🥐", "name": "Padaria", "cat": "Alimentação · Hoje", "amt": "18,50", "inc": False}]]),
dict(title="Pizza de sexta _também entra._", msgs=[["u", "pizza 59,90"], ["card", {"icon": "🍕", "name": "Pizza", "cat": "Alimentação · Hoje", "amt": "59,90", "inc": False}]]),
dict(title="Ônibus e metrô _somam._", msgs=[["u", "recarga do cartão de ônibus 50"], ["card", {"icon": "🚌", "name": "Recarga de transporte", "cat": "Transporte · Hoje", "amt": "50,00", "inc": False}]]),
dict(title="Estacionamento? _Registrado._", msgs=[["u", "estacionamento 15"], ["card", {"icon": "🅿️", "name": "Estacionamento", "cat": "Transporte · Hoje", "amt": "15,00", "inc": False}]]),
dict(title="Conta de luz _no lugar certo._", msgs=[["u", "conta de luz 187,30"], ["card", {"icon": "💡", "name": "Conta de luz", "cat": "Moradia · Hoje", "amt": "187,30", "inc": False}]]),
dict(title="Aluguel _em segundos._", msgs=[["u", "aluguel 1450"], ["card", {"icon": "🏠", "name": "Aluguel", "cat": "Moradia · Hoje", "amt": "1.450,00", "inc": False}]]),
dict(title="Internet de casa, _registrada._", msgs=[["u", "internet 99,90"], ["card", {"icon": "📶", "name": "Internet", "cat": "Moradia · Hoje", "amt": "99,90", "inc": False}]]),
dict(title="Consulta médica? _Anotada._", msgs=[["u", "consulta dermatologista 250"], ["card", {"icon": "🩺", "name": "Consulta dermatologista", "cat": "Saúde · Hoje", "amt": "250,00", "inc": False}]]),
dict(title="Show do fim de semana, _registrado._", msgs=[["u", "ingresso do show 180"], ["card", {"icon": "🎤", "name": "Ingresso do show", "cat": "Lazer · Hoje", "amt": "180,00", "inc": False}]]),
dict(title="Barzinho com amigos? _Uma mensagem._", msgs=[["u", "bar com a galera 74"], ["card", {"icon": "🍻", "name": "Bar com a galera", "cat": "Lazer · Hoje", "amt": "74,00", "inc": False}]]),
dict(title="Streaming _também é gasto._", msgs=[["u", "streaming 39,90"], ["card", {"icon": "📺", "name": "Streaming", "cat": "Lazer · Hoje", "amt": "39,90", "inc": False}]]),
dict(title="Salário caiu? _Registra a entrada._", msgs=[["u", "salário 4800"], ["card", {"icon": "💰", "name": "Salário", "cat": "Rendimentos · Hoje", "amt": "4.800,00", "inc": True}]]),
dict(title="Dinheiro de volta? _Entrada registrada._", msgs=[["u", "reembolso da empresa 230"], ["card", {"icon": "↩️", "name": "Reembolso da empresa", "cat": "Outras receitas · Hoje", "amt": "230,00", "inc": True}]]),
dict(title="Pix recebido? _Anota também._", msgs=[["u", "recebi 80 do João do churrasco"], ["card", {"icon": "🍖", "name": "João · churrasco", "cat": "Outras receitas · Hoje", "amt": "80,00", "inc": True}]]),
dict(title="Presente de casamento, _registrado._", msgs=[["u", "presente casamento Lu 200"], ["card", {"icon": "💍", "name": "Presente casamento Lu", "cat": "Presentes · Hoje", "amt": "200,00", "inc": False}]]),
dict(title="Veterinário? _No lugar certo._", msgs=[["u", "veterinário 160"], ["card", {"icon": "🐾", "name": "Veterinário", "cat": "Pet · Hoje", "amt": "160,00", "inc": False}]]),
dict(title="Banho e tosa _também._", msgs=[["u", "banho e tosa 70"], ["card", {"icon": "🛁", "name": "Banho e tosa", "cat": "Pet · Hoje", "amt": "70,00", "inc": False}]]),
dict(title="Sorvete da tarde? _Registrado._", msgs=[["u", "sorvete 14"], ["card", {"icon": "🍦", "name": "Sorvete", "cat": "Alimentação · Hoje", "amt": "14,00", "inc": False}]]),
dict(title="Feira do sábado, _anotada._", msgs=[["u", "feira 63,20"], ["card", {"icon": "🥬", "name": "Feira", "cat": "Alimentação · Hoje", "amt": "63,20", "inc": False}]]),
dict(title="Pedágio da viagem? _Uma mensagem._", msgs=[["u", "pedágio 12,40"], ["card", {"icon": "🛣️", "name": "Pedágio", "cat": "Transporte · Hoje", "amt": "12,40", "inc": False}]]),
dict(title="Gás de cozinha _registrado._", msgs=[["u", "botijão de gás 115"], ["card", {"icon": "🔥", "name": "Botijão de gás", "cat": "Moradia · Hoje", "amt": "115,00", "inc": False}]]),
dict(title="Condomínio? _Pronto._", msgs=[["u", "condomínio 620"], ["card", {"icon": "🏢", "name": "Condomínio", "cat": "Moradia · Hoje", "amt": "620,00", "inc": False}]]),
dict(title="Cinema com pipoca, _registrado._", msgs=[["u", "cinema e pipoca 78"], ["card", {"icon": "🍿", "name": "Cinema e pipoca", "cat": "Lazer · Hoje", "amt": "78,00", "inc": False}]]),
dict(title="Taxi da madrugada? _Anotado._", msgs=[["u", "táxi 42"], ["card", {"icon": "🚕", "name": "Táxi", "cat": "Transporte · Hoje", "amt": "42,00", "inc": False}]]),
dict(title="Venda do freela? _Entrada._", msgs=[["u", "recebi 650 do cliente"], ["card", {"icon": "💼", "name": "Pagamento do cliente", "cat": "Rendimentos · Hoje", "amt": "650,00", "inc": True}]]),
dict(title="Lanche no trabalho? _Uma mensagem._", msgs=[["u", "lanche da tarde 16"], ["card", {"icon": "🥪", "name": "Lanche da tarde", "cat": "Alimentação · Hoje", "amt": "16,00", "inc": False}]]),
dict(title="Exame de laboratório, _registrado._", msgs=[["u", "exame de sangue 95"], ["card", {"icon": "🧪", "name": "Exame de sangue", "cat": "Saúde · Hoje", "amt": "95,00", "inc": False}]]),
dict(title="Dentista? _No lugar certo._", msgs=[["u", "dentista 180"], ["card", {"icon": "🦷", "name": "Dentista", "cat": "Saúde · Hoje", "amt": "180,00", "inc": False}]]),
dict(title="Brinquedo pro sobrinho, _anotado._", msgs=[["u", "presente do Pedro 89"], ["card", {"icon": "🧸", "name": "Presente do Pedro", "cat": "Presentes · Hoje", "amt": "89,00", "inc": False}]]),
dict(title="Hambúrguer de domingo, _registrado._", msgs=[["u", "hambúrguer 46"], ["card", {"icon": "🍔", "name": "Hambúrguer", "cat": "Alimentação · Hoje", "amt": "46,00", "inc": False}]]),
dict(title="Açaí _também conta._", msgs=[["u", "açaí 22"], ["card", {"icon": "🍇", "name": "Açaí", "cat": "Alimentação · Hoje", "amt": "22,00", "inc": False}]]),
dict(title="Passeio no parque? _Anotado._", msgs=[["u", "entrada do parque 30"], ["card", {"icon": "🌳", "name": "Entrada do parque", "cat": "Lazer · Hoje", "amt": "30,00", "inc": False}]]),
dict(title="Rendimento? _Entra também._", msgs=[["u", "rendimento da poupança 27"], ["card", {"icon": "📈", "name": "Rendimento", "cat": "Rendimentos · Hoje", "amt": "27,00", "inc": True}]]),
dict(title="Petisco do dog, _registrado._", msgs=[["u", "petisco pro Thor 25"], ["card", {"icon": "🦴", "name": "Petisco pro Thor", "cat": "Pet · Hoje", "amt": "25,00", "inc": False}]]),
dict(title="Remédio da farmácia, _em segundos._", msgs=[["u", "remédio de alergia 33"], ["card", {"icon": "💊", "name": "Remédio de alergia", "cat": "Saúde · Hoje", "amt": "33,00", "inc": False}]]),
dict(title="Viagem de carro? _Combustível anotado._", msgs=[["u", "abasteci 250"], ["card", {"icon": "⛽", "name": "Combustível", "cat": "Transporte · Hoje", "amt": "250,00", "inc": False}]]),
dict(title="Churrasco com a família, _registrado._", msgs=[["u", "carne do churrasco 140"], ["card", {"icon": "🥩", "name": "Carne do churrasco", "cat": "Alimentação · Hoje", "amt": "140,00", "inc": False}]]),
dict(title="Conta de água? _Uma mensagem._", msgs=[["u", "água 78,60"], ["card", {"icon": "💧", "name": "Conta de água", "cat": "Moradia · Hoje", "amt": "78,60", "inc": False}]]),
dict(title="Bônus do trabalho? _Entrada._", msgs=[["u", "recebi bônus 1200"], ["card", {"icon": "🎉", "name": "Bônus", "cat": "Rendimentos · Hoje", "amt": "1.200,00", "inc": True}]]),
dict(title="Gasto de _ontem_ também dá.", sub="Registre quando lembrar.", msgs=[["u", "jantar ontem 88"], ["card", {"icon": "🍝", "name": "Jantar", "cat": "Alimentação · Hoje", "amt": "88,00", "inc": False}]]),
dict(title="Quer ver o mês? _/saldo._", msgs=[["u", "/saldo"], ["wt", "📊 **Resumo do mês**\nReceitas: R$ 3.900,00\nDespesas: R$ 1.845,20\nSaldo do mês: R$ 2.054,80"]]),
dict(title="Dica: _/receita_ para entradas.", msgs=[["u", "/receita 300 Venda"], ["card", {"icon": "🏷️", "name": "Venda", "cat": "Outras receitas · Hoje", "amt": "300,00", "inc": True}]]),
dict(title="Dica: _/despesa_ para saídas.", msgs=[["u", "/despesa 45 Livro"], ["card", {"icon": "📚", "name": "Livro", "cat": "Lazer · Hoje", "amt": "45,00", "inc": False}]]),
dict(title="Alerta de orçamento _no Telegram._", sub="Quando uma categoria chega a 80%.", msgs=[["wt", "⚠️ **Orçamento de Alimentação**\nVocê está em **82%** do limite deste mês."]]),
dict(title="Seu painel, _atualizado na hora._", sub="Registrou no Telegram, apareceu no painel.", img="dash-top"),
dict(title="Onde foi _o dinheiro do mês?_", sub="Veja as categorias lado a lado.", img="categorias"),
dict(title="Este mês _vs._ o anterior.", img="comparacao"),
dict(title="Relatórios que _mostram o caminho._", img="rel-cat"),
dict(title="Seu patrimônio _mês a mês._", img="patrimonio"),
dict(title="Quanto dá para gastar _por dia?_", img="posso-gastar"),
dict(title="Todas as transações, _num lugar só._", img="dash-bottom"),
]
